name: Publish Thunderstore Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    environment: thunderstore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
          cache: true
      - name: Install Tools
        run: dotnet tool restore
      - name: Publish to Thunderstore
        run: dotnet build -t:PublishToThunderstore -c Release -v d
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}